### ISSUE TITLE
Classing two different projects into the same group

### ISSUE THREAD

**Issue by abougouffa** [fritzgrabo/project-tab-groups#6]
First, let me thank you for this package. I'm experimenting `project-tab-groups` after experiencing some issues with `tabspaces`. I've found it pretty simple and integrates well with the built-in `project` in a cleaner way, congrats!

However, I've remarked that, in some cases, it does classify two different projects into the same tab group.

Lets imagine we have two projects:
- `~/work/project1/code/git-repo/`
- `~/work/project2/code/git-repo/`

In this case, the two projects are different, however, opening the first one will create a group for `git-repo`, then, opening the second one will switch to `git-repo` instead of creating a new `git-repo<something>` tab group.

I see that this can be fixed by tweaking the `project-tab-groups-tab-group-name-function` but I think it should be dealt with in the package itself!

Indeed, changing `project-name` to `project-root` here solves the issue:

https://github.com/fritzgrabo/project-tab-groups/blob/2658405d5f3c539fbd9ccf95297a016a2c91816a/project-tab-groups.el#L80-L82

**Comment by fritzgrabo** [comment]
@abougouffa thanks for the kind words, they're much appreciated.

The issue you describe is indeed an issue, and it's a tricky one :sweat_smile:

I originally went with `project-name` (vs. `project-root`) because it respects a user-provided `project-vc-name` variable in newer versions of Emacs. Users would set that variable in a project-local `.dir-locals.el` file to control the name of the project for display purposes, and switching to `project-root` would mean we'd lose that feature.

I'll want to look into this some more to understand what the correct place would be to make project names unique in the context of the current Emacs session. `project.el` already deals with making buffer names unique across project boundaries, so maybe its `project-name` facility should provide that option as well?

In the meantime, for your issue at hand, I suggest you try setting a (unique) project name for your git-repos using dir-local variables like described above. If your version of Emacs doesn't yet respect `project-vc-name`, you can also set `project-name` as a dir-local variable: `project-tab-groups` will pick that up and use it as the project's name.

Let me know if that helps!

**Comment by abougouffa** [comment]
Hi @fritzgrabo 

Thanks for the reply. Yes, I understand the rational behind using `project-name` and it is perfectly justifiable.

For now, I'm using the `project-name` with an extra hash calculated from the project path, this way I'm sure that I don't have collisions between tab group names even when the project name is the same.

Here my current config for reference:

```elisp
(use-package project-tab-groups
  :straight t
  :after project
  :init
  (setq project-tab-groups-tab-group-name-function #'+project-tab-groups-name-by-project-root)
  (project-tab-groups-mode 1)
  :config
  (defun +project-tab-groups-name-by-project-root (dir)
    "Derive tab group name for project in DIR."
    (with-temp-buffer
      (setq default-directory dir)
      (hack-dir-local-variables-non-file-buffer)
      (let ((name (or (and (boundp 'tab-group-name) tab-group-name)
                      (and (boundp 'project-name) project-name)
                      (and (fboundp 'project-name)
                           (when-let ((proj (project-current)))
                             (format "%s (%s)" (project-name proj) (substring (sha1 (project-root proj)) nil 8))))
                      (file-name-nondirectory (directory-file-name dir))))
            (name-template (or (and (boundp 'tab-group-name-template) tab-group-name-template)
                               (and (boundp 'project-name-template) project-name-template)
                               "%s")))
        (format name-template name)))))
```

**Comment by fritzgrabo** [comment]
Ah, I see. That's a quick and clever idea to create unique names for the projects -- I'm glad you found something to solve your immediate issue.

I'll continue to investigate when I have more time at my hands. From what I see, Emacs provides [the `uniquify` package](https://github.com/typester/emacs/blob/master/lisp/uniquify.el) to keep buffer names in the current session unique. Maybe I can wire that into project names as well somehow? Either that or file a bug for `project.el` to see what the maintainers of that package think about uniquifying project names there already.

Thanks for your input, that's all super helpful 🙌
